from _typeshed import Incomplete

from _managers import FileManager as FileManager
from _types import Book as Book

class Binder:
    book: Incomplete
    binder_type: Incomplete
    def __init__(self, book: Book) -> None: ...
    @property
    def book_name(self) -> str: ...
    @property
    def file_manager(self): ...
    @property
    def get_binder_tempfile(self) -> str: ...
    def add_binder(self, binder: dict) -> None: ...
    def update_binder(self, binder: dict) -> None: ...
    def get_binder_json(self) -> dict | list | str: ...
    @property
    def get_binder(self) -> dict: ...

class LoreBinder(Binder): ...
