from _typeshed import Incomplete

from _types import Binder as Binder
from _types import ErrorManager as ErrorManager
from book import Book

email_handler: Incomplete
file_handler: Incomplete

def extract_names(
    book: Book, binder: Binder, error_handler: ErrorManager
) -> None: ...
def analyze_names(
    book: Book, binder: Binder, error_handler: ErrorManager
) -> None: ...
def summarize_names(
    book: Book, binder: Binder, error_handler: ErrorManager
) -> None: ...
def build_lorebinder(book_dict: dict) -> dict: ...
def create_lorebinder(book_dict: dict, user_folder: str): ...
def create_folder(user: str) -> str: ...
def create_user(author: str) -> str: ...
def create_user_folder(author: str) -> str: ...
def check_file(book_dict, book_file, user_folder, metadata) -> None: ...
def make_pdf(user_folder: str, title: str) -> None: ...
def main() -> None: ...
